version: '3.0'
services:
  spring-service:
    image: sushmagowda321/spring-boot 
    ports:
      - 8085:8081
    volumes:
      - spring-vol:/usr/src/myapp

volumes:
  spring-vol:
    driver: local
